# Generated by Django 5.0.6 on 2024-06-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_continent_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='continent',
            name='populatin',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
